version: "3"
services:
  mongodb:
    image: mongo:5.0.0
    container_name: cnt_graphql
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    #   MONGO_INITDB_DATABASE: db_graphql